### ISSUE TITLE
Facing issue with `swift build`

### ISSUE THREAD

**Issue by balajiiosdev** [udacity/ios-short-s3-monolith#1]
Hi, I am facing issue with running `swift build` Any help would be appreciated. Thanks.

`In file included from /app/.build/checkouts/Perfect-LinuxBridge.git--2461238964130732388/LinuxBridge/LinuxBridge.c:2:
/app/.build/checkouts/Perfect-LinuxBridge.git--2461238964130732388/LinuxBridge/include/LinuxBridge.h:6:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h>
         ^
1 error generated.
error: terminated(1): /usr/bin/swift-build-tool -f /app/.build/debug.yaml main`

**Comment by jarrodparkes** [comment]
@balajiiosdev i pushed an update on the Docker image. try rebuilding the image (see the How To section in the README) and running the example

**Comment by ghost** [comment]
I also faced similar issue. Mine is showing this:
`root@9efa1e1a260c:/app# swift build
Compile CHTTPParser http_parser.c
Compile CHTTPParser utils.c
Compile LinuxBridge LinuxBridge.c
Compile COpenSSL openssl.c
Compile Swift Module 'LoggerAPI' (1 sources)
Compile Swift Module 'KituraTemplateEngine' (1 sources)
Compile Swift Module 'Cryptor' (10 sources)
Compile Swift Module 'Socket' (3 sources)
Compile Swift Module 'Signals' (1 sources)
Compile Swift Module 'SwiftyJSON' (2 sources)
Compile Swift Module 'PerfectThread' (3 sources)
Compile Swift Module 'PerfectLib' (10 sources)
Compile Swift Module 'HeliumLogger' (2 sources)
Compile Swift Module 'SSLService' (1 sources)
Compile Swift Module 'KituraNet' (36 sources)
Compile Swift Module 'PerfectCrypto' (7 sources)
Compile Swift Module 'Kitura' (44 sources)
Compile Swift Module 'KituraSession' (8 sources)
Compile Swift Module 'Credentials' (6 sources)
Compile Swift Module 'CredentialsHTTP' (4 sources)
Compile Swift Module 'monolith' (2 sources)
Linking ./.build/x86_64-unknown-linux/debug/monolith
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
/usr/bin/ld.gold: error: cannot find -lCOpenSSL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /app/.build/debug.yaml main`

/usr/bin/ld.gold: error: cannot find -lCOpenSSL is the main issue. Can you help me fix it? @jarrodparkes

**Comment by spearheadOne** [comment]
Hello Jarrod, 
I have the same issue when I am rebuilding monolith on swift 4

**Comment by jarrodparkes** [comment]
the linker error suggests that the environment/container you are running doesn't have access to the OpenSSL packages. for everyone who is having this issue, can you confirm which Docker image you are using and that it has OpenSSL installed?

**Comment by jarrodparkes** [comment]
also, this project should be built with the Swift 3.1 toolchain (specified by `.swift-version`) at the root of the directory. to confirm you are building the project with the proper toolchain, try running `swift -v` from the command line and see what it says.

**Comment by spearheadOne** [comment]
Here is the link to my docker file:
https://github.com/abondar24/SomeSwift/blob/master/Monolith/Dockerfile
Build on my host machine is showing the same though I have OpenSSL installed

What are the differences for Swift 4?

**Comment by jarrodparkes** [comment]
with Swift 4, the dependent packages may have changed (requiring different system packages). this is why i haven't converted this repo to use Swift 4 yet. so, to ensure things work as seen in the course, use the Swift 3.1 toolchain.

**Comment by jarrodparkes** [comment]
also, to confirm openssl is installed, try the following:

```bash
# build the image (includes openssl)
$ docker build -t s3-monolith:1.0.0 .

# run container (using the image you just built)
$ docker run --rm -it -v $(pwd):/app -p 8080:8080 s3-monolith:1.0.0 /bin/bash

# from container, see if openssl is installed
/app $ openssl
OpenSSL >

# exit openssl
OpenSSL > exit

# remove the existing build directory (if exists), and rebuild the project
/app $ rm -rf .build/
/app $ swift build
```

**Comment by spearheadOne** [comment]
Ok, I believe PerfectCrypto or some else related to security was changed on 4 , so I will double check. On 3.1 everything worked for me

**Comment by balajiiosdev** [comment]
@jarrodparkes unfortunately even after using latest Dockerfile, still i am getting below error.
`Compile COpenSSL openssl.c
In file included from /app/.build/checkouts/Perfect-LinuxBridge.git--4736433969500250620/LinuxBridge/LinuxBridge.c:2:
/app/.build/checkouts/Perfect-LinuxBridge.git--4736433969500250620/LinuxBridge/include/LinuxBridge.h:6:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h>
         ^
1 error generated.
Compile Swift Module 'Cryptor' (10 sources)
Compile Swift Module 'Socket' (3 sources)
<unknown>:0: error: build had 1 command failures
error: exit(1): /usr/bin/swift-build-tool -f /app/.build/debug.yaml`

I checked my swift -v It shows
`root@f6142ef0d517:/app# swift -v
Swift version 3.1.1 (swift-3.1.1-RELEASE)
Target: x86_64-unknown-linux-gnu
/usr/bin/lldb "--repl=-disable-objc-interop -color-diagnostics"
error: failed to launch REPL process: process launch failed: 'A' packet returned an error: 8`
and also I checked 
`root@f6142ef0d517:/app# openssl
OpenSSL> exit`
It also looks good.
But still i'm not able to compile.

**Comment by balajiiosdev** [comment]
@jarrodparkes here is another finding
I just cloned https://github.com/PerfectlySoft/Perfect-LinuxBridge.git and tried `swift build`
It showed the same error in terminal.
`Compile LinuxBridge LinuxBridge.c
In file included from /app/.build/checkouts/Perfect-LinuxBridge.git--4736433969500250620/LinuxBridge/LinuxBridge.c:2:
/app/.build/checkouts/Perfect-LinuxBridge.git--4736433969500250620/LinuxBridge/include/LinuxBridge.h:6:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h>
         ^
1 error generated.
<unknown>:0: error: build had 1 command failures
error: exit(1): /usr/bin/swift-build-tool -f /app/.build/debug.yaml`

**Comment by jarrodparkes** [comment]
@balajiiosdev my only advice right now would be the same as given in this issue (but for building with Heroku) https://github.com/kylef/heroku-buildpack-swift/issues/19 it sounds like the environment, for whatever reason, doesn't have the dependencies it needs (`uuid-dev`).

in the container environment, try running the following command:

```bash
apt-get install uuid-dev 
```

^ see if this installs anything or if the system claims that it is already installed. if you actually see that an installation is taking place, then it confirms that (1) the Dockerfile is missing the dependency or (2) the container you are using was created without the dependency.

I have reused names for containers before and this will cause issues when I rebuild an image... it will or will not contain dependencies I assume to be there. to be safe, make sure you rebuild the image from scratch.

**Comment by MrXcitement** [comment]
@balajiiosdev The error when trying to run the swift REPL and you receive:  "error: failed to launch REPL process: process launch failed: 'A' packet returned an error: 8" can be resolved by running the docker container with the --privileged flag. see here for more info at IBMs github project: https://github.com/IBM-Swift/swift-ubuntu-docker#privileged-mode.

@jarrodparkes I was able to get the monolith service running on macOS High Sierra with Docker 17.09.0-ce-mac35 (19611) installed by changing the Dockerfile to use 'FROM ibmcom/swift-ubuntu:3.1' instead of the kitura image. The kitura latest image has Swift 4 installed, so the change makes sure that the Swift 3.1 toolchain is installed. I then add the '--privileged' flag to the docker run command.

**Comment by jarrodparkes** [comment]
@MrXcitement thank you for the updates and help debugging the issues. i've tested and confirmed your changes, and I've updated the Dockerfile and instructions to reflect them too 👍

**Comment by rchatham** [comment]
@jarrodparkes I'm getting the same issue when dealing with Perfect-Crypto after trying to upgrade to current Swift, based in part on your solutions from Udacity.
 
I have the `apt-get install uuid-dev` line in the Dockerfile, but when trying to run apt-get from the shell I get the following:
```
$ sudo apt-get install uuid-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package uuid-dev
```

Any solutions for this?

Thank you.
